//go:build e2e

// Package e2e drives the full docker-compose stack through real HTTP, direct
// Postgres reads, and direct Kafka consumption — SPEC.md §10.3's TST-E2E-1..4.
// Run via `make test-e2e` after `make up`; never invoked by `make test` or CI
// (no compose orchestration there). Requires keys/private.pem to already
// exist (generated by scripts/generate-jwt.sh or any prior `make up`).
package e2e

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/twmb/franz-go/pkg/kgo"
)

const (
	walletBaseURL = "http://localhost:8080"
	ledgerBaseURL = "http://localhost:8081"
	postgresDSN   = "postgres://ledger_app:ledger_app@localhost:5432/ledger?sslmode=disable"
	kafkaBroker   = "localhost:9092"
	ledgerTopic   = "ledger.posted.v1"
	// systemAccountID mirrors ADR-0008's default SYSTEM_ACCOUNT_ID.
	systemAccountID = "00000000-0000-0000-0000-000000000001"
)

// signJWT mirrors scripts/generate-jwt.sh's claims shape (sub, role, iat,
// exp) and signing key (keys/private.pem, RS256) exactly, so tokens minted
// here are interchangeable with ones the shell script would produce.
func signJWT(t *testing.T, userID uuid.UUID, role string) string {
	t.Helper()

	keyPath := os.Getenv("E2E_PRIVATE_KEY_PATH")
	if keyPath == "" {
		keyPath = "../../keys/private.pem"
	}
	pemBytes, err := os.ReadFile(keyPath)
	if err != nil {
		t.Fatalf("read private key at %s (run scripts/generate-jwt.sh once, or `make up`, to generate it): %v", keyPath, err)
	}
	key, err := jwt.ParseRSAPrivateKeyFromPEM(pemBytes)
	if err != nil {
		t.Fatalf("parse RSA private key: %v", err)
	}

	now := time.Now()
	claims := jwt.MapClaims{
		"sub":  userID.String(),
		"role": role,
		"iat":  now.Unix(),
		"exp":  now.Add(24 * time.Hour).Unix(),
	}
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	signed, err := token.SignedString(key)
	if err != nil {
		t.Fatalf("sign JWT: %v", err)
	}
	return signed
}

func doRequest(t *testing.T, method, url, bearerToken, body string) *http.Response {
	t.Helper()
	req, err := http.NewRequest(method, url, strings.NewReader(body))
	if err != nil {
		t.Fatalf("build request: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if bearerToken != "" {
		req.Header.Set("Authorization", "Bearer "+bearerToken)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, url, err)
	}
	return resp
}

func readBody(t *testing.T, resp *http.Response) string {
	t.Helper()
	b, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read response body: %v", err)
	}
	return string(b)
}

// newWallet creates a wallet for ownerID and returns its ID. Each E2E test
// uses a fresh random ownerID per run so reruns against a warm stack never
// collide with a previous run's wallets.
func newWallet(t *testing.T, token string, ownerID uuid.UUID) uuid.UUID {
	t.Helper()
	body := fmt.Sprintf(`{"ownerId":"%s","currency":"BRL"}`, ownerID)
	resp := doRequest(t, http.MethodPost, walletBaseURL+"/wallets", token, body)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		t.Fatalf("POST /wallets = %d, want 201; body: %s", resp.StatusCode, readBody(t, resp))
	}
	var created struct {
		WalletID string `json:"walletId"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
		t.Fatalf("decode wallet creation response: %v", err)
	}
	return uuid.MustParse(created.WalletID)
}

// seedDeposit funds destinationWallet directly through the Ledger API's
// system funding account (ADR-0008's exemption) -- mirrors the overview demo
// script's step 2.
func seedDeposit(t *testing.T, destinationWallet uuid.UUID, amount string) {
	t.Helper()
	txID := uuid.New()
	body := fmt.Sprintf(
		`{"transactionId":"%s","type":"DEPOSIT","entries":[{"accountId":"%s","entryType":"DEBIT","amount":"%s"},{"accountId":"%s","entryType":"CREDIT","amount":"%s"}]}`,
		txID, systemAccountID, amount, destinationWallet, amount)
	resp := doRequest(t, http.MethodPost, ledgerBaseURL+"/ledger/postings", "", body)
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		t.Fatalf("seed deposit POST /ledger/postings = %d, want 201; body: %s", resp.StatusCode, readBody(t, resp))
	}
}

func transferBody(source, destination uuid.UUID, amount string) string {
	return fmt.Sprintf(`{"sourceWalletId":"%s","destinationWalletId":"%s","amount":"%s"}`, source, destination, amount)
}

// postTransfer issues POST /transfers with the given Idempotency-Key and
// returns the response plus its already-read body (resp.Body is consumed).
func postTransfer(t *testing.T, token, idempotencyKey string, source, destination uuid.UUID, amount string) (*http.Response, string) {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, walletBaseURL+"/transfers", strings.NewReader(transferBody(source, destination, amount)))
	if err != nil {
		t.Fatalf("build transfer request: %v", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Idempotency-Key", idempotencyKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("POST /transfers: %v", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read transfer response body: %v", err)
	}
	return resp, string(body)
}

type balanceResponse struct {
	WalletID string  `json:"walletId"`
	Balance  float64 `json:"balance"`
	Currency string  `json:"currency"`
	AsOf     string  `json:"asOf"`
	Stale    bool    `json:"stale"`
}

// pollBalance polls GET /wallets/{id}/balance every 200ms for up to 5s (the
// NFR-CONS-2 SLO) until want is reached, returning whatever it last observed
// either way so callers can assert on a timeout too. All E2E test amounts
// are whole-number BRL values, exactly representable as float64, so a direct
// equality check against want is safe here (no epsilon needed).
func pollBalance(t *testing.T, token string, walletID uuid.UUID, want float64) balanceResponse {
	t.Helper()
	deadline := time.Now().Add(5 * time.Second)
	var last balanceResponse
	for time.Now().Before(deadline) {
		resp := doRequest(t, http.MethodGet, fmt.Sprintf("%s/wallets/%s/balance", walletBaseURL, walletID), token, "")
		if resp.StatusCode == http.StatusOK {
			if err := json.NewDecoder(resp.Body).Decode(&last); err != nil {
				t.Fatalf("decode balance response: %v", err)
			}
			resp.Body.Close()
			if last.Balance == want {
				return last
			}
		} else {
			resp.Body.Close()
		}
		time.Sleep(200 * time.Millisecond)
	}
	return last
}

// assertLedgerEntryCount asserts accountID has exactly want rows in
// ledger_db.ledger_entries, connecting directly to Postgres as ledger_app
// (the same restricted role the Ledger Service itself runs as).
func assertLedgerEntryCount(t *testing.T, accountID uuid.UUID, want int) {
	t.Helper()
	conn, err := pgx.Connect(context.Background(), postgresDSN)
	if err != nil {
		t.Fatalf("connect to postgres: %v", err)
	}
	defer conn.Close(context.Background())

	var count int
	err = conn.QueryRow(context.Background(),
		"SELECT count(*) FROM ledger_db.ledger_entries WHERE account_id = $1", accountID).Scan(&count)
	if err != nil {
		t.Fatalf("query ledger_entries for account %s: %v", accountID, err)
	}
	if count != want {
		t.Errorf("ledger_entries count for account %s = %d, want %d", accountID, count, want)
	}
}

// assertLedgerEntriesForTransaction asserts transactionID has exactly want
// rows in ledger_db.ledger_entries.
func assertLedgerEntriesForTransaction(t *testing.T, transactionID uuid.UUID, want int) {
	t.Helper()
	conn, err := pgx.Connect(context.Background(), postgresDSN)
	if err != nil {
		t.Fatalf("connect to postgres: %v", err)
	}
	defer conn.Close(context.Background())

	var count int
	err = conn.QueryRow(context.Background(),
		"SELECT count(*) FROM ledger_db.ledger_entries WHERE transaction_id = $1", transactionID).Scan(&count)
	if err != nil {
		t.Fatalf("query ledger_entries for transaction %s: %v", transactionID, err)
	}
	if count != want {
		t.Errorf("ledger_entries count for transaction %s = %d, want %d", transactionID, count, want)
	}
}

// assertLedgerPostedObserved consumes ledger.posted.v1 from the start with a
// fresh consumer group (so it always sees the whole topic history) until it
// finds an event for transactionID or a 10s deadline elapses.
func assertLedgerPostedObserved(t *testing.T, transactionID uuid.UUID) {
	t.Helper()
	cl, err := kgo.NewClient(
		kgo.SeedBrokers(kafkaBroker),
		kgo.ConsumeTopics(ledgerTopic),
		kgo.ConsumeResetOffset(kgo.NewOffset().AtStart()),
		kgo.ConsumerGroup("e2e-"+uuid.New().String()),
	)
	if err != nil {
		t.Fatalf("kafka client: %v", err)
	}
	defer cl.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	for {
		fetches := cl.PollFetches(ctx)
		if ctx.Err() != nil {
			t.Fatalf("timed out waiting for LEDGER_POSTED for transaction %s on %s", transactionID, ledgerTopic)
		}
		found := false
		fetches.EachRecord(func(r *kgo.Record) {
			var event struct {
				TransactionID string `json:"transactionId"`
			}
			if err := json.Unmarshal(r.Value, &event); err == nil && event.TransactionID == transactionID.String() {
				found = true
			}
		})
		if found {
			return
		}
	}
}
